services:
  - type: web
    name: testlink-web
    runtime: docker
    plan: free
    region: oregon
    envVars:
      - key: TL_TIMEZONE
        value: America/La_Paz
      - key: PGSSLMODE
        value: require
      - key: PGOPTIONS
        value: endpoint=ep-silent-sun-afd0euia
      - key: TL_DB_HOST
        value: ep-silent-sun-afd0euia-pooler.c-2.us-west-2.aws.neon.tech
      - key: TL_DB_PORT
        value: 5432
      - key: TL_DB_NAME
        value: neondb
      - key: TL_DB_USER
        value: neondb_owner
      - key: TL_DB_PASS
        fromSecret: TL_DB_PASS
# sin sección "databases:"

#services:
#  - type: web
#    name: testlink-web
#    runtime: docker
#    plan: free
#    region: oregon
#    envVars:
#      - key: TL_TIMEZONE
#        value: America/La_Paz
#      - key: DATABASE_URL
#        fromDatabase:
#          name: testlink-db
#          property: connectionString   # <-- válido

#databases:
#  - name: testlink-db
#    plan: free
#    region: oregon