services:
  - type: web
    name: testlink-web
    runtime: docker
    plan: free
    region: oregon
    envVars:
      - key: TL_TIMEZONE
        value: America/La_Paz
      - key: DATABASE_URL
        fromDatabase:
          name: testlink-db
          property: connectionString   # <-- válido

databases:
  - name: testlink-db
    plan: free
    region: oregon